news_sites:
    eluniversal:
        url: https://www.eluniversal.com.mx
        queries:
            homepage_article_links: '.field-content a'
            article_body: '.grid-nota2'
            article_title: '.Encabezado-Articulo'
    elpais:
        url: https://elpais.com
        queries:
            homepage_article_links: '.articulo-titulo a'
            article_body: ''
            article_title: ''  